---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      deprecations_as_errors: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum install epel-release -y
        - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13 && rm install.sh

#  - name: centos-7-chef-12
#    driver_config:
#      image: centos/systemd
#      run_command: /usr/sbin/init
#      privileged: true
#      deprecations_as_errors: true
#      provision_command:
#        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
#        - systemctl enable sshd.service
#        - yum update -y
#        - yum install epel-release -y
#        - yum install https://centos7.iuscommunity.org/ius-release.rpm -y
#        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12 && rm install.sh
#
#  - name: centos-69
#    driver_config:
#      image: centos:6.9
#      privileged: true
#      provision_command:
#        - yum install epel-release -y
#        - yum install https://centos6.iuscommunity.org/ius-release.rpm -y
#        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13 && rm install.sh
#
#  - name: centos-69-chef-12
#    driver_config:
#      image: centos:6.9
#      privileged: true
#      provision_command:
#        - yum update -y
#        - yum install epel-release -y
#        - yum install https://centos6.iuscommunity.org/ius-release.rpm -y
#        - curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12 && rm install.sh

provisioner:
  name: chef_solo
  chef_license: accept-no-persist

verifier:
  name: inspec

suites:
  - name: solr-config
    run_list:
      - solr-config
